[Admission control service] Smoke tests
glaciation-heu/gitops-deployments pull request #21
Opened 2024-04-30 07:31 UTC by matthewrossi

PR related to https://github.com/glaciation-heu/IceStream/issues/156 (and based on https://github.com/glaciation-heu/gitops-deployments/pull/20).

It automates smoke tests execution after each successful ArgoCD Sync with the use of a Job running on PostSync hook.
On successful completion of the hook, the Job (and all the resources created for its functioning) are automatically removed from the cluster.

2024-05-02 11:07 UTC, ktatarnikovhiro requested changes

2024-05-02 11:07 UTC, ktatarnikovhiro commented on integration/apps/gatekeeper-smoke-tests.yaml
> +  generateName: gatekeeper-smoke-test-
I suspect `generatedName` should be `name`?

2024-05-02 11:07 UTC, ktatarnikovhiro commented on integration/apps/gatekeeper-smoke-tests.yaml
> +        command:
Something is wrong with those tests:
If I `apply` the file I am getting the errors below. Could you have a look please?
```
│ gatekeeper-smoke-test-6xlzw constrainttemplate.templates.gatekeeper.sh/k8sallowedrepos created                                                                                                       │ │
│ gatekeeper-smoke-test-6xlzw k8sallowedrepos.constraints.gatekeeper.sh/repo-is-openpolicyagent created                                                                                                │ │
│ gatekeeper-smoke-test-6xlzw Error from server (Forbidden): error when creating "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/general/allowedrepos/samples/r │ │
│ epo-must-be-openpolicyagent/example_allowed.yaml": pods "opa-allowed" is forbidden: violates PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "opa" must set securityCon │ │
│ text.allowPrivilegeEscalation=false), unrestricted capabilities (container "opa" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "opa" must set security │ │
│ Context.runAsNonRoot=true), seccompProfile (pod or container "opa" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")                                                  │ │
│ gatekeeper-smoke-test-6xlzw Error from server (Forbidden): error when creating "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/general/allowedrepos/samples/r │ │
│ epo-must-be-openpolicyagent/example_disallowed_container.yaml": pods "nginx-disallowed" is forbidden: violates PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "nginx"  │ │
│ must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container " │ │
│ nginx" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")                        │ │
│ gatekeeper-smoke-test-6xlzw Error from server (Forbidden): error when creating "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/general/allowedrepos/samples/r │ │
│ epo-must-be-openpolicyagent/example_disallowed_initcontainer.yaml": pods "nginx-disallowed" is forbidden: violates PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (containers "ng │ │
│ inxinit", "opa" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (containers "nginxinit", "opa" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot │ │
│  != true (pod or containers "nginxinit", "opa" must set securityContext.runAsNonRoot=true), seccompProfile (pod or containers "nginxinit", "opa" must set securityContext.seccompProfile.type to "Ru │ │
│ ntimeDefault" or "Localhost")                                                                                                                                                                        │ │
│ gatekeeper-smoke-test-6xlzw Error from server (Forbidden): error when creating "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/general/allowedrepos/samples/r │ │
│ epo-must-be-openpolicyagent/example_disallowed_both.yaml": pods "nginx-disallowed" is forbidden: violates PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (containers "nginxinit", │ │
│  "nginx" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (containers "nginxinit", "nginx" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != t │ │
│ rue (pod or containers "nginxinit", "nginx" must set securityContext.runAsNonRoot=true), seccompProfile (pod or containers "nginxinit", "nginx" must set securityContext.seccompProfile.type to "Run │ │
│ timeDefault" or "Localhost")                                                                                                                                                                         │ │
│ gatekeeper-smoke-test-6xlzw Error from server (NotFound): error when deleting "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/general/allowedrepos/samples/re │ │
│ po-must-be-openpolicyagent/example_allowed.yaml": pods "opa-allowed" not found                                                                                                                       │ │
│ gatekeeper-smoke-test-6xlzw Error from server (NotFound): error when deleting "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/general/allowedrepos/samples/re │ │
│ po-must-be-openpolicyagent/example_disallowed_container.yaml": pods "nginx-disallowed" not found                                                                                                     │ │
│ gatekeeper-smoke-test-6xlzw Error from server (NotFound): error when deleting "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/general/allowedrepos/samples/re │ │
│ po-must-be-openpolicyagent/example_disallowed_initcontainer.yaml": pods "nginx-disallowed" not found                                                                                                 │ │
│ gatekeeper-smoke-test-6xlzw Error from server (NotFound): error when deleting "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/general/allowedrepos/samples/re │ │
│ po-must-be-openpolicyagent/example_disallowed_both.yaml": pods "nginx-disallowed" not found                                                                                                          │ │
│ gatekeeper-smoke-test-6xlzw k8sallowedrepos.constraints.gatekeeper.sh "repo-is-openpolicyagent" deleted                                                                                              │ │
│ gatekeeper-smoke-test-6xlzw constrainttemplate.templates.gatekeeper.sh "k8sallowedrepos" deleted 
```

2024-05-02 15:28 UTC, matthewrossi commented on integration/apps/gatekeeper-smoke-tests.yaml
> +        command:
Commit dc82f6e should solve the issue :crossed_fingers: 
Unfortunately, I have no way to verify it myself because ArgoCD is working on the `main` branch.
When you have time, could you try it out? :pray:

2024-05-13 07:56 UTC, ktatarnikovhiro commented on integration/apps/gatekeeper-smoke-tests.yaml
> +  generateName: gatekeeper-smoke-test-
I am setting fixed name since generated name is difficult to manage (create/remove)

2024-05-13 07:56 UTC, ktatarnikovhiro commented on integration/apps/gatekeeper-smoke-tests.yaml
> +        command:
I've tried and it seems to be functioning

2024-05-13 07:56 UTC, merged