[data wrapping service] enable minio server-side encryption
glaciation-heu/gitops-deployments pull request #45
Opened 2024-05-10 13:54 UTC by matthewrossi

This PR depends on https://github.com/glaciation-heu/gitops-deployments/pull/44.

It updates the MinIO tenant configuration to enable server-side encryption with the integration of HaschiCorp Vault for the key management. Since the MinIO tenant depends on the deployment of the MinIO operator, here we have also anticipated the deployment of the MinIO operator to the same ArgoCD wave of the MinIO tenant.

2024-05-13 09:36 UTC, ktatarnikovhiro requested changes

2024-05-13 09:36 UTC, ktatarnikovhiro commented on integration/apps/minio-tenant.yaml
> +  name: glaciation-env-configuration
I am looking and see that this minio-tenant is very different from the one deployed from helm chart. Is there a way to deploy it from helm chart? if there is no way then I propose to make a separate tenant for data wrapping.

2024-05-13 09:36 UTC, ktatarnikovhiro commented on integration/apps/minio-tenant.yaml
> +    cert-manager.io/cluster-issuer: "private-ca-issuer"
I am afraid TLS is not available in the integration cluster in ingresses and ssl-redirect as well.

2024-05-13 17:34 UTC, matthewrossi commented on integration/apps/minio-tenant.yaml
> +  name: glaciation-env-configuration
I managed to make it work with the Helm chart

2024-05-14 11:05 UTC, matthewrossi commented on integration/apps/minio-tenant.yaml
> +    cert-manager.io/cluster-issuer: "private-ca-issuer"
We could do TLS termination at ingress (like above), and then export the service without TLS, but I would suggest to go for this solution only after checking the current ingress does not work with the integration cluster.

2024-05-16 14:27 UTC, merged

2024-05-16 14:27 UTC, ktatarnikovhiro commented on integration/apps/minio-tenant.yaml
> +    cert-manager.io/cluster-issuer: "private-ca-issuer"
I am merging it and we will see...